### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by YuFeng0930** [AY2021S2-CS2103-W16-1/tp#199]
e.g. "add_event n/CS2103 meeting sd/2021-05-27 st/15:00 ed/2021-02-27 et/17:0" cannot be entered

**Comment by litone01** [comment]
This is an invalid input, do you mean an error message should be shown?

**Comment by YuFeng0930** [comment]
Yeah correct, now is like user can't even input the thing and stuck there
