### ISSUE TITLE
Should tasks/events with all field the same (other than categories and tags) be considered as same task/event 

### ISSUE THREAD

**Issue by YuFeng0930** [AY2021S2-CS2103-W16-1/tp#374]
If changes need to be made, just simply comment out 4 lines of code in class Task and Event
![image](https://user-images.githubusercontent.com/56251951/114278446-7f691e00-9a62-11eb-9a16-2a3695237f84.png)
![image](https://user-images.githubusercontent.com/56251951/114278477-9e67b000-9a62-11eb-9ed8-b3288ed73c06.png)

**Comment by litone01** [comment]
our discussion the answer is to stay as it is?
