### ISSUE TITLE
Edit Task Sequence Diagram

### ISSUE THREAD

**Issue by YuFeng0930** [AY2021S2-CS2103-W16-1/tp#376]
![image](https://user-images.githubusercontent.com/56251951/114279376-e983c200-9a66-11eb-8b8d-bf1fabdf1e85.png)
The parser needs to be created like this:
![image](https://user-images.githubusercontent.com/56251951/114279391-07512700-9a67-11eb-8359-8d74fdf2ac49.png)

**Comment by litone01** [comment]
thanks done
